version: 2

models:
  - name: dim_contratos
    description: "Dimensão que armazena os números dos contratos firmados para a prestação de serviços terceirizados."
    
    columns:
      - name: id_contrato
        description: "Chave primária (Hash) gerada a partir do número do contrato."
        tests:
          - unique
          - not_null

      - name: numero_contrato
        description: "O número identificador oficial do contrato (ex: 123/2023)."
        tests:
          - not_null