version: 2

models:
  - name: app_terceirizados
    description: >
      Tabela final da camada ouro que reune os dados do terceirizado
      para aplicação.

    columns:

      - name: id_terceirizado
        description: Chave estrangeira para dim_terceirizado.
        tests:
          - not_null

      - name: cnpj
        description: CNPJ da empresa contratada (mantido como string).
        tests:
          - not_null

      - name: cpf
        description: CPF do terceirizado (mantido como string).
        tests:
          - not_null

      - name: orgao_superior_sigla
        description: "Sigla do órgão superior (ex: MEC, MS, MD)."
