version: 2

models:
  - name: dim_terceirizados
    description: >
      Dimensão de terceirizado na camada prata.
      Contém dados cadastrais consolidados provenientes
      da tabela brutos_terceirizados.
      Modelo incremental com estratégia merge,
      utilizando id_terceirizado como chave única.

    columns:

      - name: id_terceirizado
        description: Identificador único do terceirizado.
        tests:
          - not_null
          - unique

      - name: cpf
        description: CPF do terceirizado mantido como string.
        tests:
          - not_null

      - name: cnpj
        description: CNPJ da empresa contratada mantido como string.
        tests:
          - not_null

      - name: terceirizado_nome
        description: Nome completo do terceirizado.

      - name: razao_social
        description: Razão social da empresa contratada.

      - name: id_categoria_profissional
        description: Código numérico da categoria profissional.
        tests:
          - not_null

      - name: escolaridade
        description: Nível de escolaridade do terceirizado.
