version: 2

models:
  - name: dim_orgaos_superiores
    description: "Dimensão que contém os Órgãos Superiores (Unidades Gestoras). É o nível mais alto da hierarquia de órgãos."
    
    columns:
      - name: id_orgao_superior
        description: "Chave primária (Hash) gerada a partir do nome e código da Unidade Gestora Superior."
        tests:
          - unique
          - not_null

      - name: orgao_superior_sigla
        description: "Sigla do órgão superior (ex: MEC, MS, MD)."

      - name: unidade_gestora_codigo
        description: "Código numérico identificador da Unidade Gestora."
        tests:
          - not_null

      - name: unidade_gestora_nome
        description: "Nome completo da Unidade Gestora correspondente ao Órgão Superior."
        tests:
          - not_null